// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjffgplfonsvbzukjkzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqZmZncGxmb25zdmJ6dWtqa3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzk1OTAsImV4cCI6MjA2MDkxNTU5MH0.Q1LTHkxCrBhXW_zK6w2QPUVHIbj52A4iv0KLH72qx0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);